class UserAlreadyExistsError(Exception):
    detail = "User already exists"